name: strange-matter-engine
channels:
  - conda-forge
dependencies:
  - python=3.11
  - rdkit
  - jupyterlab
  - ipywidgets
  - pandas
  - numpy
  - matplotlib
  - networkx
  - nbformat
  - nbconvert
