name: strange-matter-gpu
channels:
  - conda-forge
dependencies:
  - python=3.11
  - rdkit
  - pandas
  - numpy
  - matplotlib
  - networkx
  - pip
  - pip:
      - --index-url https://download.pytorch.org/whl/cu128
      - torch==2.11.0+cu128
