"""Second question bank for the Strange Matter Engine fundamentals examination."""

QUESTIONS = [
    # Chemistry and molecular representation (1-12)
    {
        "domain": "Chemistry",
        "question": "What is the total formal charge of a deprotonated carboxylate group, COO−?",
        "options": ["Minus one", "Minus two", "Zero"],
        "correct": 0,
        "explanation": "The carboxylate group has one excess electron overall. Resonance distributes this minus-one charge across the two oxygens; it does not create two full negative charges.",
    },
    {
        "domain": "Chemistry",
        "question": "Why should protonation state be defined before molecular features are generated?",
        "options": ["It can alter formal charge, hydrogen-bonding behaviour and electronic structure", "It changes every carbon atom into nitrogen", "It determines the experimental CYP concentration"],
        "correct": 0,
        "explanation": "Adding or removing a proton can change formal charge, donor/acceptor status, aromatic descriptions and the initial graph features.",
    },
    {
        "domain": "Chemistry",
        "question": "Why is an aromatic bond not adequately described as an ordinary fixed single bond?",
        "options": ["Its bonding participates in a delocalised aromatic system", "It contains no electrons", "It can occur only between oxygen atoms"],
        "correct": 0,
        "explanation": "Aromatic bond annotations represent delocalised bonding within an aromatic system rather than one localised single bond.",
    },
    {
        "domain": "Chemistry",
        "question": "Which quantity is naturally defined for the complete molecule rather than one atom?",
        "options": ["Molecular weight", "Atomic number", "Atom hybridisation"],
        "correct": 0,
        "explanation": "Molecular weight is obtained from the entire composition. Atomic number and hybridisation describe individual atoms.",
    },
    {
        "domain": "Chemistry",
        "question": "What does a rotatable-bond count attempt to summarise?",
        "options": ["A component of molecular conformational flexibility", "The total formal charge", "The number of CYP enzymes inhibited"],
        "correct": 0,
        "explanation": "Rotatable bonds provide a simple topological proxy for conformational flexibility, subject to a precise chemical definition.",
    },
    {
        "domain": "Chemistry",
        "question": "Why can stereochemistry matter even when two molecules have the same atom connectivity?",
        "options": ["Different spatial arrangements can interact differently with a chiral protein environment", "Stereochemistry changes every atomic number", "Connectivity uniquely fixes every three-dimensional arrangement"],
        "correct": 0,
        "explanation": "Stereoisomers share connectivity but differ spatially. Proteins are chiral environments and can distinguish those arrangements.",
    },
    {
        "domain": "Chemistry",
        "question": "An IC50 of 1 micromolar equals 10⁻⁶ molar. What is its pIC50?",
        "options": ["6", "Minus 6", "1"],
        "correct": 0,
        "explanation": "pIC50 = -log10(10^-6) = 6.",
    },
    {
        "domain": "Chemistry",
        "question": "How much lower is the IC50 of a compound with pIC50 7 than one with pIC50 5?",
        "options": ["One hundred times lower", "Two times lower", "Seven-fifths lower"],
        "correct": 0,
        "explanation": "A difference of two logarithmic units corresponds to 10^2 = 100-fold in molar IC50.",
    },
    {
        "domain": "Chemistry",
        "question": "Why must a pIC50 value be stored with its CYP target?",
        "options": ["Inhibition potency is specific to the molecule–target assay context", "A molecule has a universal pIC50 independent of protein", "The target determines the molecule's atomic numbers"],
        "correct": 0,
        "explanation": "The same molecule may inhibit different CYP enzymes with different potencies, so target identity is part of the label context.",
    },
    {
        "domain": "Chemistry",
        "question": "Which system can be conjugated without being aromatic?",
        "options": ["An open-chain sequence of overlapping p orbitals", "A saturated isolated methane molecule", "Any atom with sp3 hybridisation only"],
        "correct": 0,
        "explanation": "Conjugation can extend along an acyclic chain. Aromaticity additionally requires a suitable cyclic, planar electron system.",
    },
    {
        "domain": "Chemistry",
        "question": "What is the principal limitation of using electronegativity alone as the initial scalar atom state?",
        "options": ["Atoms of the same element begin identically despite different chemical environments", "Electronegativity cannot be represented numerically", "It already contains the experimental pIC50"],
        "correct": 0,
        "explanation": "Element electronegativity ignores charge, hybridisation, aromaticity and bonding context. It is useful for teaching but chemically incomplete.",
    },
    {
        "domain": "Chemistry",
        "question": "What does a canonical SMILES representation not provide by itself?",
        "options": ["A measured bound three-dimensional conformation in a CYP active site", "A specification of molecular connectivity", "Element identities for represented atoms"],
        "correct": 0,
        "explanation": "Canonical SMILES standardises a text representation of molecular structure; it is not an experimentally observed protein-bound pose.",
    },

    # Graph theory and encoding (13-22)
    {
        "domain": "Graphs and encoding",
        "question": "For an ordinary covalent molecular graph, why is its adjacency matrix usually symmetric?",
        "options": ["A bond connecting i to j also connects j to i", "Every atom has the same degree", "All bonds have order one"],
        "correct": 0,
        "explanation": "The molecular graph is normally undirected: A_ij and A_ji describe the same bond.",
    },
    {
        "domain": "Graphs and encoding",
        "question": "What operation does D⁻¹A perform on a vector of atom states?",
        "options": ["It replaces each row with the mean state of that atom's neighbours", "It sums every molecule in the dataset", "It one-hot encodes the atom elements"],
        "correct": 0,
        "explanation": "Row i of D^-1 A divides the adjacency entries by degree d_i, producing the neighbour mean for atom i.",
    },
    {
        "domain": "Graphs and encoding",
        "question": "Why does a sum aggregator and a mean aggregator respond differently to node degree?",
        "options": ["A sum grows with the number of messages, whereas a mean normalises by neighbour count", "A mean removes all neighbour information", "A sum can operate only on aromatic atoms"],
        "correct": 0,
        "explanation": "Summation retains information about message multiplicity; averaging reduces direct scaling with degree.",
    },
    {
        "domain": "Graphs and encoding",
        "question": "What information is available to a local message Mθ(x_i, x_j, e_ij)?",
        "options": ["The receiving state, sending state and their bond attributes", "Every held-out experimental label", "Only the global molecule count"],
        "correct": 0,
        "explanation": "The message is local to an adjacent atom pair and may condition communication on the chemical edge.",
    },
    {
        "domain": "Graphs and encoding",
        "question": "What does permutation equivariance mean for atom-level states?",
        "options": ["Renumbering input atoms renumbers output atom states in the same way", "Renumbering atoms changes the chemistry", "All atom outputs must be identical"],
        "correct": 0,
        "explanation": "An equivariant atom-level transformation follows a consistent reindexing without changing physical content.",
    },
    {
        "domain": "Graphs and encoding",
        "question": "What does permutation invariance require of a molecule-level readout?",
        "options": ["Its output is unchanged by consistent atom renumbering", "It returns one value per atom index", "It sorts molecules by molecular weight"],
        "correct": 0,
        "explanation": "A molecular property cannot depend on the arbitrary order assigned to atoms.",
    },
    {
        "domain": "Graphs and encoding",
        "question": "After one strictly local message-passing generation, which atoms can directly influence atom i?",
        "options": ["Atom i and its immediate neighbours", "Every atom in every molecule", "Only atoms two bonds away"],
        "correct": 0,
        "explanation": "One generation communicates across one edge. More distant influence requires repeated generations.",
    },
    {
        "domain": "Graphs and encoding",
        "question": "After T local generations, what is the maximum topological distance from which information can ordinarily reach atom i?",
        "options": ["T bonds", "One bond regardless of T", "The molecular weight in bonds"],
        "correct": 0,
        "explanation": "Each local generation can extend the receptive field by one graph edge.",
    },
    {
        "domain": "Graphs and encoding",
        "question": "Why must every molecule use the same ordering of feature channels?",
        "options": ["A shared parameter must encounter the same chemical meaning in each column", "Every molecule must contain the same elements", "Channel ordering determines pIC50 experimentally"],
        "correct": 0,
        "explanation": "If column meanings changed between molecules, shared weights would act on inconsistent quantities.",
    },
    {
        "domain": "Graphs and encoding",
        "question": "What problem does an explicit 'Other' category address in one-hot encoding?",
        "options": ["It provides a defined representation for categories outside the chosen vocabulary", "It makes missing labels part of the test set", "It converts all elements into carbon"],
        "correct": 0,
        "explanation": "A closed vocabulary needs a documented fallback rather than silently misencoding an unseen element or hybridisation.",
    },

    # Cellular automata and emergence (23-32)
    {
        "domain": "Cellular automata",
        "question": "What trajectory does the transparent diffusion rule produce when alpha equals zero?",
        "options": ["Every state remains equal to its initial value", "Every atom immediately becomes the neighbour mean", "The graph loses all edges"],
        "correct": 0,
        "explanation": "With alpha = 0, the transition is the identity: X^(t+1) = X^(t).",
    },
    {
        "domain": "Cellular automata",
        "question": "What does the transparent rule do when alpha equals one?",
        "options": ["Each next atom state is its current neighbour mean", "Each atom retains only its own state", "Every state becomes pIC50"],
        "correct": 0,
        "explanation": "At alpha = 1, the self-retention term vanishes and only the neighbour average remains.",
    },
    {
        "domain": "Cellular automata",
        "question": "What happens to the derivative of tanh when its input is strongly saturated?",
        "options": ["It approaches zero", "It approaches infinity", "It becomes exactly the atom degree"],
        "correct": 0,
        "explanation": "d tanh(u)/du = 1 - tanh²(u), which becomes small near output values minus one or one.",
    },
    {
        "domain": "Cellular automata",
        "question": "What is the direct effect of a shared positive bias in the scalar parameterised rule?",
        "options": ["It shifts every atom's preactivation upward at every generation", "It creates a new bond at every atom", "It reduces the trajectory length"],
        "correct": 0,
        "explanation": "The same additive bias enters each cell update before tanh.",
    },
    {
        "domain": "Cellular automata",
        "question": "What behaviour can a negative neighbour coefficient encourage?",
        "options": ["A response opposing the sign of the aggregated neighbour state", "Guaranteed molecular consensus", "Removal of stereochemistry from the graph"],
        "correct": 0,
        "explanation": "A negative coefficient makes positive neighbour messages contribute negatively and vice versa, potentially promoting contrast or alternation.",
    },
    {
        "domain": "Cellular automata",
        "question": "Why is parameter sharing scientifically important to the graph CA?",
        "options": ["It asserts that one local law governs all cells and generations", "It assigns a unique law to every atom index", "It prevents any molecule from having rings"],
        "correct": 0,
        "explanation": "The model searches for a transferable local transition rather than memorising atom-index-specific rules.",
    },
    {
        "domain": "Cellular automata",
        "question": "Why could asynchronous updates create an unwanted dependency?",
        "options": ["Later updates may use already changed states, making update order part of the dynamics", "They force every bond to become aromatic", "They remove all nonlinearities"],
        "correct": 0,
        "explanation": "Unless explicitly intended, arbitrary atom ordering should not affect a molecular trajectory.",
    },
    {
        "domain": "Cellular automata",
        "question": "What remains fixed when the same graph-CA rule is applied to molecules of different sizes?",
        "options": ["The parameter values and channel semantics", "The number of atoms", "The graph adjacency matrix"],
        "correct": 0,
        "explanation": "Molecular topology and n vary, while the local rule and feature definitions are shared.",
    },
    {
        "domain": "Cellular automata",
        "question": "What role do chemical atom features play at generation zero?",
        "options": ["They provide chemically informed initial conditions for subsequent dynamics", "They prove the final prediction is causal", "They determine the validation error without learning"],
        "correct": 0,
        "explanation": "The initial state seeds the automaton with local chemistry; the learned transition then transforms and propagates that information.",
    },
    {
        "domain": "Cellular automata",
        "question": "What would invalidate a claim that a pattern is emergent?",
        "options": ["The pattern was inserted directly as a global target-dependent feature", "The pattern arose after repeated local updates", "The pattern was measured across the trajectory"],
        "correct": 0,
        "explanation": "Emergence concerns global behaviour generated by local interactions, not a global answer supplied directly to every cell.",
    },

    # Dynamics and fingerprints (33-47)
    {
        "domain": "Dynamics",
        "question": "For n atoms with d state channels, what is the dimension of the flattened global state space?",
        "options": ["n times d", "n plus d", "d divided by n"],
        "correct": 0,
        "explanation": "X has n by d entries, so vectorising it gives a point in R^(nd).",
    },
    {
        "domain": "Dynamics",
        "question": "Which equation defines a fixed point X* of transition F?",
        "options": ["F(X*) = X*", "F(X*) = 0 for every system", "F(X*) = pIC50"],
        "correct": 0,
        "explanation": "A fixed point is unchanged by one application of the dynamical rule.",
    },
    {
        "domain": "Dynamics",
        "question": "What relation characterises a period-two orbit that is not a fixed point?",
        "options": ["F(F(X)) = X while F(X) differs from X", "F(X) = X", "F(X) is undefined"],
        "correct": 0,
        "explanation": "The state returns after two updates but alternates between two distinct states.",
    },
    {
        "domain": "Dynamics",
        "question": "If the exact step distance becomes zero, what has happened for a deterministic update?",
        "options": ["The current state maps to itself and is a fixed point", "A chaotic attractor has been proven", "The molecule has no atoms"],
        "correct": 0,
        "explanation": "Zero distance means X^(t+1) = X^(t); deterministic repetition then remains at that fixed state.",
    },
    {
        "domain": "Dynamics",
        "question": "Why does d_t below a nonzero tolerance not prove an exact fixed point?",
        "options": ["The state may still be moving by a small but nonzero amount", "The norm cannot compare two states", "Tolerance changes the molecular graph"],
        "correct": 0,
        "explanation": "Numerical convergence is an operational approximation and must be distinguished from exact equality.",
    },
    {
        "domain": "Dynamics",
        "question": "What kind of observation is convergence time when no convergence occurs before the simulation ends?",
        "options": ["Right-censored by the trajectory window", "An exact observation at T+1", "A missing molecular bond"],
        "correct": 0,
        "explanation": "We know only that convergence time exceeds the observed window; the actual future time is unknown.",
    },
    {
        "domain": "Dynamics",
        "question": "Why can a large oscillation amplitude fail to establish periodicity?",
        "options": ["Large excursions need not repeat with a consistent period", "Amplitude is defined only for fixed points", "Periodicity requires zero variance"],
        "correct": 0,
        "explanation": "Amplitude measures range, whereas periodicity concerns repeated temporal structure.",
    },
    {
        "domain": "Dynamics",
        "question": "What would high autocorrelation at lag p suggest?",
        "options": ["The signal resembles itself after p generations", "Every atom has degree p", "The ridge penalty equals p"],
        "correct": 0,
        "explanation": "Lag-p autocorrelation measures similarity between x_t and x_(t-p).",
    },
    {
        "domain": "Dynamics",
        "question": "Why should a dominant Fourier peak be interpreted cautiously?",
        "options": ["Finite windows and transients can create spectral concentration without a true periodic attractor", "Fourier transforms contain no frequency information", "A peak proves the trajectory is a fixed point"],
        "correct": 0,
        "explanation": "Spectral evidence is useful but depends on window length, sampling and stationarity of the analysed regime.",
    },
    {
        "domain": "Dynamics",
        "question": "What can a trajectory entropy measure attempt to summarise?",
        "options": ["The diversity or unpredictability of observed state patterns", "The molecule's exact binding pose", "The count of formal charges only"],
        "correct": 0,
        "explanation": "Entropy-based summaries quantify distributions or symbolic patterns, but their meaning depends on binning and estimator choices.",
    },
    {
        "domain": "Dynamics",
        "question": "What property should a molecule-level dynamical fingerprint have under atom renumbering?",
        "options": ["It should remain unchanged", "It should be multiplied by the new first atom index", "It should reverse the trajectory"],
        "correct": 0,
        "explanation": "Molecule-level summaries should not depend on arbitrary node labels.",
    },
    {
        "domain": "Dynamics",
        "question": "Can step-to-step convergence occur while atoms retain different final state values?",
        "options": ["Yes; a heterogeneous fixed pattern can stop changing", "No; convergence always means atom consensus", "Only if the graph has no bonds"],
        "correct": 0,
        "explanation": "Temporal stationarity and spatial uniformity are different properties.",
    },
    {
        "domain": "Dynamics",
        "question": "What is the basin of attraction?",
        "options": ["The set of initial states whose trajectories approach a given attractor", "The list of atoms in one aromatic ring", "The training subset of one CYP only"],
        "correct": 0,
        "explanation": "An attractor's basin describes which starting conditions flow toward it.",
    },
    {
        "domain": "Dynamics",
        "question": "What makes an attractor local rather than global?",
        "options": ["It attracts a neighbourhood of initial states but not necessarily all possible states", "It is stored on only one atom", "It exists for exactly one generation"],
        "correct": 0,
        "explanation": "A local attractor has a restricted basin; other starting regions may approach different regimes.",
    },
    {
        "domain": "Dynamics",
        "question": "Why might transient length be predictively useful even when all trajectories eventually reach similar sinks?",
        "options": ["The route and time taken can preserve molecule-dependent dynamical information", "A sink erases the molecular graph before the transient", "Transient length is identical to molecular weight"],
        "correct": 0,
        "explanation": "Endpoint-only representations may miss distinctions encoded in how quickly and through what patterns the endpoint is approached.",
    },

    # Perturbations and stability (48-55)
    {
        "domain": "Stability",
        "question": "If delta₀ = 10⁻⁴ and delta₂ = 10⁻³, what is the two-step finite-time rate?",
        "options": ["One half times ln(10)", "Minus ln(10)", "Exactly zero"],
        "correct": 0,
        "explanation": "lambda_2 = (1/2) ln(delta_2/delta_0) = (1/2) ln(10), which is positive.",
    },
    {
        "domain": "Stability",
        "question": "Why is periodic perturbation rescaling used in standard largest-Lyapunov estimation?",
        "options": ["It keeps separation in the local regime while accumulating growth rates", "It changes the attractor into a sink", "It removes the need to specify a norm"],
        "correct": 0,
        "explanation": "Without rescaling, separations can saturate at system size and cease to measure local exponential growth.",
    },
    {
        "domain": "Stability",
        "question": "Why can two distance norms give different finite-time divergence values?",
        "options": ["They weight the components of state-space separation differently", "Only one norm can accept numerical states", "A norm changes the experimental label"],
        "correct": 0,
        "explanation": "Finite-dimensional norms are related asymptotically, but finite-time magnitudes and estimates can still differ.",
    },
    {
        "domain": "Stability",
        "question": "What problem appears when trajectory separation reaches the numerical precision floor?",
        "options": ["Further contraction cannot be resolved reliably", "The graph gains infinite degree", "The loss becomes an experimental measurement"],
        "correct": 0,
        "explanation": "Round-off limits make extremely small differences indistinguishable from zero or numerical noise.",
    },
    {
        "domain": "Stability",
        "question": "Under an adequate long-term protocol, what does a positive largest Lyapunov exponent support?",
        "options": ["Sustained exponential sensitivity to nearby initial conditions", "Guaranteed high pIC50", "Convergence to a stable sink"],
        "correct": 0,
        "explanation": "A robust positive largest exponent is characteristic evidence of sensitive chaotic dynamics, within the analysed invariant regime.",
    },
    {
        "domain": "Stability",
        "question": "What perturbation behaviour is expected near a strongly stable sink?",
        "options": ["Nearby separations contract toward zero", "Every separation grows without bound", "The atom elements change"],
        "correct": 0,
        "explanation": "Local stability means sufficiently nearby trajectories return toward the attracting fixed point.",
    },
    {
        "domain": "Stability",
        "question": "Why must a multichannel perturbation protocol state which channel was changed?",
        "options": ["Sensitivity may differ among chemical and free dynamical directions", "All channels are necessarily identical", "The channel determines the number of CYP targets"],
        "correct": 0,
        "explanation": "Different state-space directions can have different local growth or contraction rates.",
    },
    {
        "domain": "Stability",
        "question": "Why should perturbed and reference trajectories use the same molecular graph and parameters?",
        "options": ["The experiment should isolate sensitivity to initial state rather than other changes", "Different graphs are required to define distance", "Parameters cannot be shared between trajectories"],
        "correct": 0,
        "explanation": "A controlled perturbation changes one defined factor while holding the transition system fixed.",
    },

    # Backpropagation and learning the CA (56-63)
    {
        "domain": "Backpropagation",
        "question": "If x = tanh(u), what local derivative is used during backpropagation?",
        "options": ["1 minus x squared", "x squared plus one", "The atom degree only"],
        "correct": 0,
        "explanation": "d tanh(u)/du = 1 - tanh²(u) = 1 - x².",
    },
    {
        "domain": "Backpropagation",
        "question": "For L = one half times (ŷ − y)², what is dL/dŷ?",
        "options": ["ŷ minus y", "y divided by ŷ", "Two regardless of the prediction"],
        "correct": 0,
        "explanation": "Differentiating the half squared residual gives the residual itself.",
    },
    {
        "domain": "Backpropagation",
        "question": "What does the adjoint at generation t represent?",
        "options": ["The sensitivity of the final loss to the state at generation t", "The molecule's adjacency matrix", "The ridge intercept"],
        "correct": 0,
        "explanation": "The backward adjoint is the gradient dL/dX^(t).",
    },
    {
        "domain": "Backpropagation",
        "question": "What is the purpose of gradient clipping?",
        "options": ["Limit excessively large update signals", "Guarantee the global optimum", "Convert regression targets into classes"],
        "correct": 0,
        "explanation": "Clipping can stabilise optimisation when gradient norms explode, but it does not guarantee optimal learning.",
    },
    {
        "domain": "Backpropagation",
        "question": "Why is a longer unrolled trajectory not automatically better for learning?",
        "options": ["It can increase cost and worsen vanishing or exploding gradients while adding redundant states", "It always removes every transient", "It changes pIC50 into IC50"],
        "correct": 0,
        "explanation": "Trajectory length is a hyperparameter balancing useful temporal information, computation and gradient conditioning.",
    },
    {
        "domain": "Backpropagation",
        "question": "If theta_self is used at every generation, how is its total gradient formed?",
        "options": ["By summing its contribution from every generation", "By keeping only the final generation's contribution", "By averaging atom indices"],
        "correct": 0,
        "explanation": "The loss depends on the shared parameter through every occurrence in the unrolled graph.",
    },
    {
        "domain": "Backpropagation",
        "question": "What does a finite-difference gradient check test?",
        "options": ["Whether analytical derivatives agree with small numerical loss changes", "Whether the held-out set has enough CYP targets", "Whether SMILES is canonical"],
        "correct": 0,
        "explanation": "Comparing analytical gradients with [L(theta+h)-L(theta-h)]/(2h) is a powerful implementation check.",
    },
    {
        "domain": "Backpropagation",
        "question": "What is a likely consequence of a learning rate that is much too large?",
        "options": ["Parameter updates may overshoot and make optimisation unstable", "All gradients become mathematically exact", "The graph becomes permutation-dependent"],
        "correct": 0,
        "explanation": "The learning rate scales the update; excessive steps can oscillate or diverge even when gradients are correct.",
    },

    # Ridge regression (64-69)
    {
        "domain": "Ridge regression",
        "question": "What model is recovered when ridge lambda equals zero and the inverse exists?",
        "options": ["Ordinary least-squares linear regression", "Logistic classification", "A cellular automaton with no states"],
        "correct": 0,
        "explanation": "Removing the L2 penalty leaves the least-squares objective.",
    },
    {
        "domain": "Ridge regression",
        "question": "Why is ridge regression useful when fingerprint components are strongly correlated?",
        "options": ["It stabilises coefficient estimation by penalising large solutions", "It deletes every correlated feature automatically", "It makes the target independent of the features"],
        "correct": 0,
        "explanation": "The lambda I term improves conditioning and reduces unstable coefficient magnitudes under multicollinearity.",
    },
    {
        "domain": "Ridge regression",
        "question": "If Z has N rows and p columns, what shape does ZᵀZ have?",
        "options": ["p by p", "N by N", "N by p"],
        "correct": 0,
        "explanation": "Z^T is p by N, so Z^T Z is p by p and acts in coefficient space.",
    },
    {
        "domain": "Ridge regression",
        "question": "After feature standardisation, what does a ridge coefficient describe most directly?",
        "options": ["Prediction change associated with a one-standard-deviation feature change, conditional on the others", "The feature's original physical unit", "A guaranteed causal effect"],
        "correct": 0,
        "explanation": "Standardised coefficients are scale-comparable associations within the fitted model, not causal estimates.",
    },
    {
        "domain": "Ridge regression",
        "question": "Where should lambda be selected in a predictive workflow?",
        "options": ["Using training data and an inner validation procedure", "Using the blinded test labels", "From the largest atom index"],
        "correct": 0,
        "explanation": "Hyperparameter selection must be isolated from the final held-out evaluation to avoid optimistic bias.",
    },
    {
        "domain": "Ridge regression",
        "question": "What trade-off typically occurs as ridge regularisation strengthens?",
        "options": ["Bias increases while variance can decrease", "Both bias and variance must become zero", "Training error must always decrease"],
        "correct": 0,
        "explanation": "Shrinkage constrains flexibility: it can improve generalisation by accepting some bias in exchange for reduced variance.",
    },

    # Validation and scientific inference (70-75)
    {
        "domain": "Validation",
        "question": "How many test folds are produced by leave-one-molecule-out validation on 12 molecules?",
        "options": ["12", "4", "1"],
        "correct": 0,
        "explanation": "Each molecule serves once as the held-out observation, producing 12 fitted folds.",
    },
    {
        "domain": "Validation",
        "question": "What is the main purpose of a chemically grouped split?",
        "options": ["Test transfer across a defined structural or biological separation", "Make training and test molecules duplicates", "Guarantee a lower RMSE"],
        "correct": 0,
        "explanation": "Grouping prevents closely related observations from making the prediction task unrealistically easy.",
    },
    {
        "domain": "Validation",
        "question": "Why is scaling the complete dataset before cross-validation leakage?",
        "options": ["Held-out feature distributions influence the training transformation", "Scaling always uses pIC50 labels", "Cross-validation forbids numerical features"],
        "correct": 0,
        "explanation": "Means and standard deviations must be learned within each training fold, then applied unchanged to its held-out fold.",
    },
    {
        "domain": "Validation",
        "question": "What makes a baseline comparison fair?",
        "options": ["The models use the same folds, labels and evaluation metrics", "The new model receives the test labels", "The baseline is intentionally under-tuned"],
        "correct": 0,
        "explanation": "A controlled comparison changes the representation or model of interest while holding evaluation conditions constant.",
    },
    {
        "domain": "Validation",
        "question": "Why report variability across seeds or resampled splits?",
        "options": ["A single score can conceal instability due to sampling and optimisation", "Variability proves data leakage", "Seeds change the chemical structures"],
        "correct": 0,
        "explanation": "Repeated evaluations show whether an apparent advantage is robust or dependent on one favourable random outcome.",
    },
    {
        "domain": "Validation",
        "question": "If the dynamical fingerprint performs worse than the descriptor baseline, what is the strongest justified conclusion?",
        "options": ["This fingerprint and evaluation do not yet demonstrate added predictive value", "All graph cellular automata are scientifically impossible", "The experimental pIC50 values must be wrong"],
        "correct": 0,
        "explanation": "A negative result applies to the tested representation, training and data regime. It motivates diagnosis without supporting universal claims.",
    },
]

assert len(QUESTIONS) == 75
assert all(len(item["options"]) == 3 and item["correct"] in (0, 1, 2) for item in QUESTIONS)
